### ISSUE TITLE
When configuring using my own custom network and geocoder I am unable to route to location.

### ISSUE THREAD

**Issue by texasgis** [SpatialAgent/directions#3]
When I select the geolocation button it zooms to my location but does not route.  I receive the following error from console.  I'm using AGS Portal 10.3 with my own custom geocoder and network.  Should it pass an x,y location if unable to geocode?

Error: Cannot perform query. Invalid query parameters. {code: 400, message: "Cannot perform query. Invalid query parameters.", details: Array[1], log: undefined, httpCode: 400…}init.js:192 xinit.js:191 (anonymous function)init.js:76 cinit.js:76 dinit.js:77 b.Deferred.resolve.callbackinit.js:76 cinit.js:76 dinit.js:77 b.Deferred.resolve.callbackinit.js:76 cinit.js:76 dinit.js:77 b.Deferred.resolve.callbackinit.js:76 cinit.js:76 dinit.js:77 b.Deferred.resolve.callbackinit.js:195 (anonymous function)init.js:199 kinit.js:199 minit.js:201 f.resolveinit.js:200 ainit.js:200 kinit.js:199 minit.js:201 f.resolveinit.js:200 ainit.js:200 kinit.js:199 minit.js:201 f.resolveinit.js:200 ainit.js:200 kinit.js:199 minit.js:201 f.resolveinit.js:160 qinit.js:164 f
main.js:782 Cannot perform query. Invalid query parameters.

**Comment by SpatialAgent** [comment]
@texasgis Can you try it with your custom geocoder but the Esri routing service?  Based on your message, I'm not sure if the custom geocoder or the custom routing service is causing the issue.

**Comment by SpatialAgent** [comment]
Updated code to resolve issue in the next release.
