### ISSUE TITLE
Defaults to km?

### ISSUE THREAD

**Issue by geofinne** [SpatialAgent/directions#4]
I'm using your Directions app template inside ArcGIS Online and I can't figure out how to configure it to display miles instead of km inside the directions box. Is there a way to fix this without downloading the code and deploying it on our server? I'm hoping it's something simple that I missed. Here's a screenshot: 
![km](https://cloud.githubusercontent.com/assets/11874166/7071499/5513cc46-deab-11e4-9b20-ae4cb3c40b76.PNG)

**Comment by SpatialAgent** [comment]
@geofinne This is an issue with the Directions widget in the API and will be addressed in the next release.  The default units will be based on the locale settings of the browser.

**Comment by geofinne** [comment]
Thanks for being able to add a config option for units in the July release!

**Comment by SpatialAgent** [comment]
Updated code to override distance units in next release.
